name: PR CI

on:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        php: [8.0]
        experimental: [false]
#         include:
#           - php: 8.1
#             experimental: true

    name: PHP${{ matrix.php }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-suggest --no-interaction --optimize-autoloader

  - name: Check codestyle
    run: vendor/bin/ecs check --config=easy-coding-standard.php --no-progress-bar .

    - name: Execute tests
      run: vendor/bin/phpunit --testdox --colors=always --coverage-text

    - name: Run Infection mutation tests for added and modified files
      run: |
        git fetch --depth=1 origin $GITHUB_BASE_REF
        php vendor/bin/infection -j2 --git-diff-filter=AM --logger-github

    - name: Build the Docker image
      run: docker build . --tag jeroeng/hummingbird:test
